name: Terraform LocalStack CI

on:
  push:
    branches:
      - main
      - Feature/Localstack
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    services:
      localstack:
        image: localstack/localstack
        ports:
          - 4566:4566
        options: --health-cmd "curl -f http://localhost:4566/_localstack/health || exit 1" --health-interval 5s --health-timeout 2s --health-retries 20

    env:
      AWS_ACCESS_KEY_ID: "test"
      AWS_SECRET_ACCESS_KEY: "test"
      DESTROY_RESOURCES: ${{ secrets.DESTROY_RESOURCES }} # Defina essa variável como "true" ou "false" no GitHub Secrets

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_wrapper: false

    - name: Initialize Terraform
      run: terraform init

    - name: Terraform Plan
      run: terraform plan

    - name: Terraform Apply
      run: terraform apply -auto-approve

    - name: Terraform Destroy
      if: env.DESTROY_RESOURCES == 'false'
      run: terraform destroy -auto-approve
